version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "boilerplate"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iiouext0nbyj"
s3_prefix = "boilerplate"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
