AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-nodejs14.x

  Sample SAM Template for lambda-nodejs14.x
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:   
  Function:
    Timeout: 500

Resources:
  SignupFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Signup
      CodeUri: lambdas/signup
      Handler: app.lambdaHandler
      Timeout: 900
      Layers:
        - !Ref LibLayer
        - !Ref CodeLayer
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        SignupApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /signup
            Method: ANY

  LoginFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Login
      CodeUri: lambdas/login
      Handler: app.lambdaHandler
      Timeout: 900
      Layers:
        - !Ref LibLayer
        - !Ref CodeLayer
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        LoginApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /login
            Method: ANY

  ProfileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Profile
      CodeUri: lambdas/profile
      Handler: app.lambdaHandler
      Timeout: 900
      Layers:
        - !Ref LibLayer
        - !Ref CodeLayer
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        ProfileApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile
            Method: ANY

  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lib
      Description: common npm libraries (used by the code layer or lambdas)
      ContentUri: shared/lib/
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete

  CodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: code
      Description: common code that lambdas can share
      ContentUri: shared/code/
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Delete

